// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwnrdldsrbgcibtkjuyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bnJkbGRzcmJnY2lidGtqdXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1OTE0NTgsImV4cCI6MjA1MDE2NzQ1OH0.5Tz6VW9fnM8X3J8akCloTmiWfLjPvswMYJyw9MCOkH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);